import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";
import NavBar from "@/components/Navbar/page";

// Use Poppins font
const poppins = Poppins({
    weight: ["400", "500", "600", "700"], // You can specify the weights you want
    subsets: ["latin"],
    variable: "--font-doto", // This will allow you to use the font with a variable
});

export const metadata: Metadata = {
    title: "Shop.co",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} antialiased`}>
                <NavBar />
                {children}
            </body>
        </html>
    );
}
